### ISSUE TITLE
Loader doesn't work on prod?

### ISSUE THREAD

**Issue by SchuylerGood** [qhacks/qhacks-website-2024#31]

**Comment by SchuylerGood** [comment]
Fix the Loader to work when the site is loading on mobile, since the ThreeJS stuff doesn't render there.

**Comment by jtepp** [comment]
fixed in [this commit](https://github.com/qhacks/qhacks-website-2024/commit/45a6c10bc90710ab3c291339d5d5f061d2e97a57) to deployment bug fixing branch

**Comment by jtepp** [comment]
fixed in [this commit](https://github.com/qhacks/qhacks-website-2024/commit/45a6c10bc90710ab3c291339d5d5f061d2e97a57) to deployment bug fixing branch
